# ---------------------------------------------------------------------------- #
# Monte Carlo battery for the CCT-2025 estimator in bRunching.
#
# Purpose:
#   Stress-test ccn(method = "cct") across six DGPs varying the error
#   distribution, bunching rate, covariate strength, and sample size. For
#   two DGPs, compare CCT against the CCN "symmetric" estimator to see
#   where location-scale buys over symmetry.
#
# Inputs:   (none — simulates data)
# Outputs:
#   - tests/mc/cct_battery_results.csv
#   - printed summary table to stdout with pass/fail verdict per DGP
#
# Dependencies: devtools (for load_all), bRunching (source in this repo),
#               stats (rnorm/rbinom/quantile — base R). No sn dependency:
#               skew errors are generated by a two-component normal mixture.
#
# Target parameter:  beta(0+) = 1.5  (all DGPs)
# Pass criterion (per DGP, CCT): |bias| < 3 * empirical_SD / sqrt(B)
#                                (DGP 5 "weak Z" is allowed to fail).
# ---------------------------------------------------------------------------- #

suppressPackageStartupMessages({
  library(devtools)
  library(stats)
})

set.seed(20260417L)

# ---- Locate the package root from this script ------------------------------ #
# Use a relative-ish path that still works when sourced directly. We rely on
# the script being at <root>/tests/mc/cct_battery.R.
this_script <- tryCatch(
  normalizePath(sys.frame(1)$ofile, mustWork = FALSE),
  error = function(e) NA_character_
)
if (is.na(this_script) || !nzchar(this_script)) {
  # Fallback: assume the caller set the working directory to the package root.
  pkg_root <- getwd()
} else {
  pkg_root <- normalizePath(file.path(dirname(this_script), "..", ".."))
}
if (!file.exists(file.path(pkg_root, "DESCRIPTION"))) {
  # Last-resort fallback for interactive runs.
  pkg_root <- "/Users/hsantanna/Library/Mobile Documents/com~apple~CloudDocs/work/research/brunching"
}

out_csv <- file.path(pkg_root, "tests", "mc", "cct_battery_results.csv")

cat("Loading bRunching from:", pkg_root, "\n")
suppressMessages(devtools::load_all(pkg_root, quiet = TRUE))

# ---- Configuration --------------------------------------------------------- #
BETA_STRUCTURAL <- 1.5     # coefficient on X * (X > 0) in the DGP (structural)
B_MC      <- 100L          # replications per DGP
N_DEFAULT <- 5000L         # per-rep sample size (except DGP 6)
GLOBAL_RUNTIME_BUDGET_SEC <- 600  # if runtime so far exceeds this, skip DGP 6
N_CALIB   <- 200000L       # sample size for per-DGP CCT-estimand calibration
B_CALIB   <- 3L            # replications for per-DGP calibration
# NOTE: the CCT estimand beta(0+) (Prop 5.1) equals the structural 1.5 only
# when Assumption 7 and the symmetry implicit in the DGP both hold. For DGP3
# (skew) the population-scale Prop 5.1 expression gives a different value.
# We therefore calibrate the true CCT estimand per DGP and report bias
# relative to BOTH the structural 1.5 and the true CCT estimand.

# ---- Helpers --------------------------------------------------------------- #

# Skew-normal-like draw via two-component normal mixture with asymmetric
# weights. The mixture is normalized to have zero median and unit-ish scale,
# then shifted so the empirical median is zero (satisfying alpha_star = 0.5).
# This substitutes for sn::rsn (not installed in this environment).
rskew <- function(n, right_skew = TRUE) {
  p  <- 0.75                                # weight on the "narrow" component
  mu1 <- if (right_skew) -0.35 else  0.35   # narrow component mean
  mu2 <- if (right_skew)  1.05 else -1.05   # broad, heavier-tail component mean
  s1  <- 0.6
  s2  <- 1.3
  comp <- rbinom(n, 1, p)                   # 1 = narrow, 0 = broad
  z <- comp * rnorm(n, mu1, s1) + (1 - comp) * rnorm(n, mu2, s2)
  # Re-center to zero median so that alpha_star = 0.5 still satisfies
  # H^{-1}(alpha_star) = 0 in the boundary quantile condition.
  z - stats::median(z)
}

# Run one Monte Carlo rep for a DGP closure.
one_rep <- function(dgp_fn, method = "cct",
                    alpha_star_val = 0.5,
                    alpha_grid_val = NULL,
                    alpha_s_val    = NULL,
                    boot_B_val     = 0L) {
  sim <- dgp_fn()
  df  <- data.frame(y = sim$y, x = sim$x, z = sim$z)

  if (method == "cct") {
    fit <- tryCatch(
      ccn("y", "x", "z", df,
          method     = "cct",
          alpha_star = alpha_star_val,
          alpha_grid = alpha_grid_val,
          alpha_s    = alpha_s_val,
          boot_B     = boot_B_val,
          seed       = NULL),
      error = function(e) list(beta = NA_real_, error = conditionMessage(e))
    )
  } else if (method == "symmetric") {
    fit <- tryCatch(
      ccn("y", "x", "z", df, method = "symmetric"),
      error = function(e) list(beta = NA_real_, error = conditionMessage(e))
    )
  } else {
    stop("unknown method: ", method)
  }

  if (is.null(fit$beta) || length(fit$beta) == 0) return(NA_real_)
  unname(fit$beta[1])
}

# Summarize a vector of beta_hats into bias / SD / RMSE / pass-flag.
# Bias is computed relative to `true_beta`. If `structural_beta` is supplied
# and differs from `true_beta`, we also report bias relative to the structural
# parameter for diagnostic purposes.
summarise_reps <- function(beta_hats,
                           true_beta = BETA_STRUCTURAL,
                           structural_beta = BETA_STRUCTURAL,
                           allow_fail = FALSE) {
  ok  <- is.finite(beta_hats)
  Bok <- sum(ok)
  if (Bok < 3L) {
    return(data.frame(
      B_ok = Bok, beta_true = true_beta, bias = NA_real_,
      bias_vs_structural = NA_real_, sd = NA_real_, rmse = NA_real_,
      mc_se_bias = NA_real_, pass = FALSE, allow_fail = allow_fail
    ))
  }
  b    <- mean(beta_hats[ok]) - true_beta
  bs   <- mean(beta_hats[ok]) - structural_beta
  sdh  <- stats::sd(beta_hats[ok])
  rmse <- sqrt(mean((beta_hats[ok] - true_beta)^2))
  mc_se_bias <- sdh / sqrt(Bok)
  pass <- abs(b) < 3 * mc_se_bias
  data.frame(
    B_ok = Bok, beta_true = true_beta, bias = b,
    bias_vs_structural = bs, sd = sdh, rmse = rmse,
    mc_se_bias = mc_se_bias, pass = pass, allow_fail = allow_fail
  )
}

# Calibrate the true CCT estimand beta(0+) for a DGP using Prop 5.1 at
# a large sample size. `dgp_fn_with_mz` must return a list with $y, $x, $z,
# and $mz (the per-obs true m(Z_i)).
calibrate_true_beta <- function(dgp_fn_with_mz, n_big = N_CALIB, B = B_CALIB) {
  betas <- numeric(B)
  for (b in seq_len(B)) {
    s <- dgp_fn_with_mz(n_big)
    ok <- s$x > 0
    if (sum(ok) < 100L) { betas[b] <- NA_real_; next }
    fit <- stats::lm(s$y[ok] ~ s$x[ok])
    gamma_0 <- coef(fit)[1L]
    gamma_1 <- coef(fit)[2L]
    # Delta = E[Y | X = 0] - gamma_0 (= lim_{x->0+} E[Y | X = x])
    Delta <- mean(s$y[s$x == 0]) - gamma_0
    # pi = (E[m(Z)] - E[X]) / P(X = 0)
    pi <- (mean(s$mz) - mean(s$x)) / mean(s$x == 0)
    betas[b] <- unname(gamma_1 - Delta / pi)
  }
  mean(betas, na.rm = TRUE)
}

# ---- DGP definitions (closures returning $y, $x, $z) ----------------------- #

# Each DGP factory takes `n` and returns a list with $y, $x, $z, $mz (where
# mz is the per-obs value of m(Z_i), used for population-scale calibration).
dgp1_baseline <- function(n = N_DEFAULT, K = 20L) {
  Z <- sample.int(K, n, replace = TRUE)
  mu_z <- -0.5 + 0.15 * Z
  eta  <- rnorm(n)
  x_star <- mu_z + eta
  x <- pmax(x_star, 0)
  y <- 2 + 0.8 * x_star + BETA_STRUCTURAL * x * (x > 0) + rnorm(n)
  list(y = y, x = x, z = Z, mz = mu_z)
}

dgp2_heterosk <- function(n = N_DEFAULT, K = 20L) {
  Z <- sample.int(K, n, replace = TRUE)
  mu_z  <- -0.5 + 0.15 * Z
  sig_z <- 0.5 + Z / 20
  eta   <- rnorm(n, 0, sig_z)
  x_star <- mu_z + eta
  x <- pmax(x_star, 0)
  y <- 2 + 0.8 * x_star + BETA_STRUCTURAL * x * (x > 0) + rnorm(n)
  list(y = y, x = x, z = Z, mz = mu_z)
}

dgp3_skew <- function(n = N_DEFAULT, K = 20L) {
  Z <- sample.int(K, n, replace = TRUE)
  mu_z <- -0.5 + 0.15 * Z
  eta  <- rskew(n, right_skew = TRUE)     # zero-median asymmetric noise
  x_star <- mu_z + eta
  x <- pmax(x_star, 0)
  y <- 2 + 0.8 * x_star + BETA_STRUCTURAL * x * (x > 0) + rnorm(n)
  list(y = y, x = x, z = Z, mz = mu_z)
}

dgp4_highbunch <- function(n = N_DEFAULT, K = 10L) {
  # Heavy overall bunching (~50%) with alpha_star = 0.85 and noise
  # shifted so H^{-1}(0.85) = 0. m(z) kept strictly positive so the
  # short-circuit m_hat(z) = q_hat(z; alpha*) is correct in all cells.
  # Per-cell bunching ranges roughly 30-65%; overall ~50%.
  shift <- qnorm(0.85)
  Z <- sample.int(K, n, replace = TRUE)
  mu_z <- 0.5 + 0.1 * Z           # m(z) in (0.6, 1.5), all positive
  eta  <- rnorm(n) - shift
  x_star <- mu_z + eta
  x <- pmax(x_star, 0)
  y <- 2 + 0.8 * x_star + BETA_STRUCTURAL * x * (x > 0) + rnorm(n)
  list(y = y, x = x, z = Z, mz = mu_z)
}

dgp5_weakZ <- function(n = N_DEFAULT, K = 3L) {
  Z <- sample.int(K, n, replace = TRUE)
  mu_z <- -0.2 + 0.05 * Z
  eta  <- rnorm(n)
  x_star <- mu_z + eta
  x <- pmax(x_star, 0)
  y <- 2 + 0.8 * x_star + BETA_STRUCTURAL * x * (x > 0) + rnorm(n)
  list(y = y, x = x, z = Z, mz = mu_z)
}

# DGP 6 is a grid over n — run per-n via a factory.
dgp6_large_n <- function(n) function() dgp1_baseline(n = n, K = 20L)

# ---- Run the battery ------------------------------------------------------- #

all_rows <- list()
t0 <- Sys.time()

# ---- One-time calibration of true CCT estimand per DGP --------------------- #
# The CCT estimand beta(0+) (per Prop 5.1) does NOT always equal the structural
# coefficient 1.5 — e.g. under skew eta (DGP3), Assumption 7's quantitative
# implications change. We calibrate per DGP at large n using the Prop 5.1
# plug-in formula on population quantities.
cat("Calibrating true CCT estimand per DGP (n = ", N_CALIB, ", B = ", B_CALIB, ") ... ",
    sep = "")
true_betas <- list(
  DGP1 = calibrate_true_beta(dgp1_baseline),
  DGP2 = calibrate_true_beta(dgp2_heterosk),
  DGP3 = calibrate_true_beta(dgp3_skew),
  DGP4 = calibrate_true_beta(dgp4_highbunch),
  DGP5 = calibrate_true_beta(dgp5_weakZ)
)
cat("done.\n")
for (nm in names(true_betas)) {
  cat(sprintf("  %s: true beta(0+) = %.4f (structural = %.4f)\n",
              nm, true_betas[[nm]], BETA_STRUCTURAL))
}

run_dgp <- function(name, dgp_fn, methods = c("cct"),
                    alpha_star_val = 0.5,
                    alpha_grid_val = NULL,
                    alpha_s_val    = NULL,
                    true_beta = BETA_STRUCTURAL,
                    B = B_MC,
                    allow_fail = FALSE,
                    note = "") {
  cat(sprintf("\n=== %s (B = %d, methods: %s) ===\n",
              name, B, paste(methods, collapse = ", ")))
  cat(sprintf("    CCT target (Prop 5.1 estimand): %.4f   |   structural (symmetric target): %.4f\n",
              true_beta, BETA_STRUCTURAL))
  for (m in methods) {
    # CCT estimates beta(0+) (Prop 5.1). The CCN "symmetric" estimator
    # targets the pooled structural slope; evaluate it against that.
    truth_m <- if (m == "cct") true_beta else BETA_STRUCTURAL
    beta_hats <- rep(NA_real_, B)
    t_start <- Sys.time()
    for (b in seq_len(B)) {
      beta_hats[b] <- one_rep(dgp_fn, method = m,
                              alpha_star_val = alpha_star_val,
                              alpha_grid_val = alpha_grid_val,
                              alpha_s_val    = alpha_s_val,
                              boot_B_val     = 0L)
    }
    dt <- as.numeric(difftime(Sys.time(), t_start, units = "secs"))
    s  <- summarise_reps(beta_hats,
                         true_beta = truth_m,
                         structural_beta = BETA_STRUCTURAL,
                         allow_fail = allow_fail)
    row <- cbind(
      dgp = name, method = m, runtime_sec = round(dt, 2),
      s, note = note, stringsAsFactors = FALSE
    )
    cat(sprintf("  method=%-9s  truth=%.4f  B_ok=%3d  bias=%+7.4f  (vs struct 1.5: %+7.4f)  SD=%6.4f  RMSE=%6.4f  MCse(bias)=%6.4f  pass=%s\n",
                m, truth_m, s$B_ok, s$bias, s$bias_vs_structural,
                s$sd, s$rmse, s$mc_se_bias, s$pass))
    all_rows[[length(all_rows) + 1L]] <<- row
  }
}

# ---- DGP 1: Baseline (homoskedastic normal) ----
run_dgp("DGP1_baseline", dgp1_baseline, methods = "cct",
        true_beta = true_betas$DGP1,
        note = "homoskedastic normal; alpha_star = 0.5")

# ---- DGP 2: Heteroskedastic ----
run_dgp("DGP2_heterosk", dgp2_heterosk, methods = "cct",
        true_beta = true_betas$DGP2,
        note = "sigma(Z) = 0.5 + Z/20")

# ---- DGP 3: Skew-normal eta (CCT vs symmetric) ----
# NOTE: under skew eta, the CCT estimand beta(0+) differs from the structural
# 1.5. Pass/fail on CCT is measured against the calibrated true estimand.
run_dgp("DGP3_skew", dgp3_skew, methods = c("cct", "symmetric"),
        true_beta = true_betas$DGP3,
        note = "right-skew mixture, zero-median")

# ---- DGP 4: High bunching (alpha_star = 0.85) ----
# Default alpha_star = 0.5 is infeasible when most mass is below zero. Use
# alpha_star = 0.85 with a grid that respects the strict-inequality checks
# in ccn_cct (alpha_grid and alpha_s must lie in (alpha_star, 1)).
run_dgp("DGP4_highbunch", dgp4_highbunch, methods = "cct",
        alpha_star_val = 0.85,
        alpha_grid_val = seq(0.88, 0.98, by = 0.02),
        alpha_s_val    = 0.98,
        true_beta = true_betas$DGP4,
        note = "60%+ censored; alpha_star = 0.85")

# ---- DGP 5: Weak Z (small K, small signal) ----
run_dgp("DGP5_weakZ", dgp5_weakZ, methods = c("cct", "symmetric"),
        true_beta = true_betas$DGP5,
        allow_fail = TRUE,
        note = "K = 3, m(z) slope 0.05 -- fragile by design")

# ---- DGP 6: Large-n consistency grid ----
elapsed_so_far <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
if (elapsed_so_far > GLOBAL_RUNTIME_BUDGET_SEC) {
  cat(sprintf("\n[skip] DGP6 large-n consistency: elapsed %.1fs > budget %ds\n",
              elapsed_so_far, GLOBAL_RUNTIME_BUDGET_SEC))
} else {
  for (n_big in c(1000L, 5000L, 20000L)) {
    run_dgp(sprintf("DGP6_n%05d", n_big), dgp6_large_n(n_big),
            methods = "cct",
            true_beta = true_betas$DGP1,
            note = sprintf("baseline DGP with n = %d", n_big))
  }
}

# ---- Aggregate and write CSV ----------------------------------------------- #
results <- do.call(rbind, all_rows)
rownames(results) <- NULL
# Reorder columns for readability.
col_order <- c("dgp", "method", "B_ok", "beta_true", "bias",
               "bias_vs_structural", "sd", "rmse",
               "mc_se_bias", "pass", "allow_fail", "runtime_sec", "note")
results <- results[, col_order]

dir.create(dirname(out_csv), showWarnings = FALSE, recursive = TRUE)
write.csv(results, out_csv, row.names = FALSE)

# ---- Print final summary --------------------------------------------------- #
total_dt <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
cat("\n\n==================== FINAL SUMMARY ====================\n")
cat(sprintf("Total runtime: %.1f seconds (%.2f minutes)\n",
            total_dt, total_dt / 60))
cat(sprintf("Structural parameter (DGP coef on X*(X>0)): %.4f\n", BETA_STRUCTURAL))
cat(sprintf("Replications per DGP (MC): B = %d\n", B_MC))
cat("Bias is reported relative to the calibrated CCT estimand (Prop 5.1).\n")
cat("'bias_vs_structural' is the (diagnostic) bias relative to 1.5.\n")
cat("Pass criterion: |bias| < 3 * SD / sqrt(B_ok)\n\n")

# Pretty-print
fmt_row <- function(r) {
  verdict <- if (isTRUE(r$pass)) "PASS"
             else if (isTRUE(r$allow_fail)) "FAIL(allowed)"
             else                  "FAIL"
  sprintf("  %-18s  %-9s  B=%3d  truth=%.4f  bias=%+7.4f  SD=%6.4f  RMSE=%6.4f  [%s]",
          r$dgp, r$method, r$B_ok, r$beta_true, r$bias, r$sd, r$rmse, verdict)
}
for (i in seq_len(nrow(results))) {
  cat(fmt_row(results[i, , drop = FALSE]), "\n", sep = "")
}

# Highlight CCT-vs-symmetric comparisons (DGPs 3 and 5).
cat("\n--- CCT vs symmetric (where both were run) ---\n")
cmp <- subset(results, dgp %in% unique(results$dgp[results$method == "symmetric"]))
for (d in unique(cmp$dgp)) {
  sub <- cmp[cmp$dgp == d, ]
  if (nrow(sub) == 2L && all(c("cct", "symmetric") %in% sub$method)) {
    cct_rmse <- sub$rmse[sub$method == "cct"]
    sym_rmse <- sub$rmse[sub$method == "symmetric"]
    winner <- if (is.finite(cct_rmse) && is.finite(sym_rmse)) {
      if (cct_rmse < sym_rmse) "CCT" else "symmetric"
    } else "N/A"
    cat(sprintf("  %s: CCT RMSE=%.4f  |  symmetric RMSE=%.4f  ->  winner: %s\n",
                d, cct_rmse, sym_rmse, winner))
  }
}

cat(sprintf("\nResults written to: %s\n", out_csv))

# Overall pass/fail: all non-allowed rows must pass.
hard_fail <- results$method == "cct" &
             !isTRUE(all(results$pass)) &
             !results$allow_fail &
             !results$pass
hard_fail <- results[results$method == "cct" & !results$allow_fail & !results$pass, ]
if (nrow(hard_fail) == 0L) {
  cat("\n>>> OVERALL: all CCT DGPs passed (ignoring allow_fail rows). <<<\n")
} else {
  cat(sprintf("\n>>> OVERALL: %d hard-fail row(s): %s <<<\n",
              nrow(hard_fail), paste(hard_fail$dgp, collapse = ", ")))
}
